---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    data_bags_path: test/fixtures/data_bags
    roles_path: test/fixtures/roles
    attributes:
      packagist:
        parameters:
          database_user: default
          database_name: default
          database_password: default
        nelmio_solarium:
          clients:
            default:
              dsn: 'http://localhost:8080/solr/packagist'
      solr_app:
        url: 'http://archive.apache.org/dist/lucene/solr/3.6.2/apache-solr-3.6.2.tgz'
      php-fpm:
        pools:
          www:
            listen: '127.0.0.1:9000'
      application_solr:
        cores:
          packagist:
            schema_xml: https://raw.githubusercontent.com/composer/packagist/master/doc/schema.xml
    run_list:
      - recipe[test_packagist]
      - role[db_master]
      - recipe[packagist]
