name             'packagist'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures packagist'
long_description 'Installs/Configures packagist'
version          '0.1.0'

depends 'php'
depends 'composer'
depends 'git'
depends 'nginx'
depends 'php-fpm'
