name             'packagist'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures packagist'
long_description 'Installs/Configures packagist'
version          '0.1.5'

depends 'application_solr'
depends 'build-essential'
depends 'certificate'
depends 'composer'
depends 'discovery'
depends 'git'
depends 'hostname'
depends 'nginx'
depends 'php'
depends 'php-fpm'
depends 'redisio'
depends 'rabbitmq'
depends 'vagrant-ohai-plugin'
