name             'test_packagist'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures test_packagist'
long_description 'Installs/Configures test_packagist'
version          '0.1.0'

depends 'apt'
depends 'build-essential'
depends 'database'
depends 'chef-solo-search'
depends 'packagist'
depends 'redisio'
depends 'solr_app'
depends 'hostsfile'
